[project]
name = "lifespan"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "mcp[cli]>=1.13.0",
    "sqlalchemy>=2.0.43",
    "pydantic-settings>=2.3.4",
    "aiosqlite>=0.20.0",
]

[project.optional-dependencies]
dev = [
    "mypy>=1.17.1",
    "pytest>=8.4.1",
    "pytest-asyncio>=1.1.0",
    "pytest-cov>=6.2.1",
    "ruff>=0.12.9",
]
