[project]
name = "mcp-server-demo"
version = "0.1.0"
description = "MCP Server showcase with local database access"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastmcp>=2.11.3",
    "sqlalchemy>=2.0.43",
    "pydantic-settings>=2.3.4",
    "aiosqlite>=0.20.0",
]

[project.optional-dependencies]
dev = [
    "pytest>=8.4.1",
    "pytest-asyncio>=1.1.0",
    "mypy>=1.17.1",
    "ruff>=0.12.9",
]
