[project]
name = "mcp-people-database"
description = "People Database MCP Server"
version = "0.1.0"

dependencies = [
    "fastmcp>=2.11.3",
    "pydantic>=2.0.0",
    "pydantic-settings>=2.3.4",
    "sqlalchemy>=2.0.43",
    "aiosqlite>=0.20.0",
    "faker>=37.6.0",
]
