[project]
name = "mcp-server"
version = "0.1.0"
description = "Valantic STI Hackathon 2025 MCP Server Example"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "mcp[cli]>=1.13.0",
    "pandas>=2.3.1",
    "pyarrow>=21.0.0",
]

[dependency-groups]
dev = [
    "ruff>=0.12.9",
]
